<a href="https://colab.research.google.com/github/divyansh1195/Halliburton-Landmark-Learning/blob/master/Data%20Science%20using%20Python(Halliburton)/Time_Series_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Time Series: Sequence of data points daily, weekly, hourly and quaterly(iscree time data points)
#It predicts future sequence based on previous observed occurances. It understands past trends so that we can forcast and plan for the future.
#Hence, in Time seies Analysis, the only variable is time.
#Time Series accounts for Autocorrelation, which is also affected by earlier observed values.

In [2]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns
from datetime import datetime

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
#select a date range
date_rng=pd.date_range(start='1/1/2020', end='31/12/2020', freq='H') #this date range has time stamps with hourly frequency.
date_rng

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00', '2020-01-01 07:00:00',
               '2020-01-01 08:00:00', '2020-01-01 09:00:00',
               ...
               '2020-12-30 15:00:00', '2020-12-30 16:00:00',
               '2020-12-30 17:00:00', '2020-12-30 18:00:00',
               '2020-12-30 19:00:00', '2020-12-30 20:00:00',
               '2020-12-30 21:00:00', '2020-12-30 22:00:00',
               '2020-12-30 23:00:00', '2020-12-31 00:00:00'],
              dtype='datetime64[ns]', length=8761, freq='H')

In [4]:
len(date_rng)

8761

In [5]:
#check the first element
type(date_rng[0])

pandas._libs.tslibs.timestamps.Timestamp

In [6]:
date_rng[0]

Timestamp('2020-01-01 00:00:00', freq='H')

**CREATE AN EXAMPLE DATAFRAME WITH TIME STAMP DATA**

In [7]:
df=pd.DataFrame(date_rng, columns=['date'])
df['data']=np.random.randint(0,100, size=(len(date_rng)))
df.head(10)

                 date  data
0 2020-01-01 00:00:00    77
1 2020-01-01 01:00:00    31
2 2020-01-01 02:00:00    65
3 2020-01-01 03:00:00    10
4 2020-01-01 04:00:00    43
5 2020-01-01 05:00:00    61
6 2020-01-01 06:00:00    64
7 2020-01-01 07:00:00    86
8 2020-01-01 08:00:00    78
9 2020-01-01 09:00:00     0

**CONVERT THE DATAFRAME INDEX TO DATE TIME INDEX**

In [8]:
df['datetime']=pd.to_datetime(df['date'])
df=df.set_index('datetime')
df.drop(['date'], axis=1, inplace=True)
df.head()

                     data
datetime
2020-01-01 00:00:00    77
2020-01-01 01:00:00    31
2020-01-01 02:00:00    65
2020-01-01 03:00:00    10
2020-01-01 04:00:00    43

In [9]:
#for time series manipulation dataframe is indexed to date time index

**SOMETIMES THE TIME STAMPS IN DATA ARE NOT NUMERICAL**

In [10]:
#convert date_rng to a list of strings
string_date_rng=[str(x) for x in date_rng]
string_date_rng

['2020-01-01 00:00:00',
 '2020-01-01 01:00:00',
 '2020-01-01 02:00:00',
 '2020-01-01 03:00:00',
 '2020-01-01 04:00:00',
 '2020-01-01 05:00:00',
 '2020-01-01 06:00:00',
 '2020-01-01 07:00:00',
 '2020-01-01 08:00:00',
 '2020-01-01 09:00:00',
 '2020-01-01 10:00:00',
 '2020-01-01 11:00:00',
 '2020-01-01 12:00:00',
 '2020-01-01 13:00:00',
 '2020-01-01 14:00:00',
 '2020-01-01 15:00:00',
 '2020-01-01 16:00:00',
 '2020-01-01 17:00:00',
 '2020-01-01 18:00:00',
 '2020-01-01 19:00:00',
 '2020-01-01 20:00:00',
 '2020-01-01 21:00:00',
 '2020-01-01 22:00:00',
 '2020-01-01 23:00:00',
 '2020-01-02 00:00:00',
 '2020-01-02 01:00:00',
 '2020-01-02 02:00:00',
 '2020-01-02 03:00:00',
 '2020-01-02 04:00:00',
 '2020-01-02 05:00:00',
 '2020-01-02 06:00:00',
 '2020-01-02 07:00:00',
 '2020-01-02 08:00:00',
 '2020-01-02 09:00:00',
 '2020-01-02 10:00:00',
 '2020-01-02 11:00:00',
 '2020-01-02 12:00:00',
 '2020-01-02 13:00:00',
 '2020-01-02 14:00:00',
 '2020-01-02 15:00:00',
 '2020-01-02 16:00:00',
 '2020-01-02 17:00:00',
 '2020-01-02 18:00:00',
 '2020-01-02 19:00:00',
 '2020-01-02 20:00:00',
 '2020-01-02 21:00:00',
 '2020-01-02 22:00:00',
 '2020-01-02 23:00:00',
 '2020-01-03 00:00:00',
 '2020-01-03 01:00:00',
 '2020-01-03 02:00:00',
 '2020-01-03 03:00:00',
 '2020-01-03 04:00:00',
 '2020-01-03 05:00:00',
 '2020-01-03 06:00:00',
 '2020-01-03 07:00:00',
 '2020-01-03 08:00:00',
 '2020-01-03 09:00:00',
 '2020-01-03 10:00:00',
 '2020-01-03 11:00:00',
 '2020-01-03 12:00:00',
 '2020-01-03 13:00:00',
 '2020-01-03 14:00:00',
 '2020-01-03 15:00:00',
 '2020-01-03 16:00:00',
 '2020-01-03 17:00:00',
 '2020-01-03 18:00:00',
 '2020-01-03 19:00:00',
 '2020-01-03 20:00:00',
 '2020-01-03 21:00:00',
 '2020-01-03 22:00:00',
 '2020-01-03 23:00:00',
 '2020-01-04 00:00:00',
 '2020-01-04 01:00:00',
 '2020-01-04 02:00:00',
 '2020-01-04 03:00:00',
 '2020-01-04 04:00:00',
 '2020-01-04 05:00:00',
 '2020-01-04 06:00:00',
 '2020-01-04 07:00:00',
 '2020-01-04 08:00:00',
 '2020-01-04 09:00:00',
 '2020-01-04 10:00:00',
 '2020-01-04 11:00:00',
 '2020-01-04 12:00:00',
 '2020-01-04 13:00:00',
 '2020-01-04 14:00:00',
 '2020-01-04 15:00:00',
 '2020-01-04 16:00:00',
 '2020-01-04 17:00:00',
 '2020-01-04 18:00:00',
 '2020-01-04 19:00:00',
 '2020-01-04 20:00:00',
 '2020-01-04 21:00:00',
 '2020-01-04 22:00:00',
 '2020-01-04 23:00:00',
 '2020-01-05 00:00:00',
 '2020-01-05 01:00:00',
 '2020-01-05 02:00:00',
 '2020-01-05 03:00:00',
 '2020-01-05 04:00:00',
 '2020-01-05 05:00:00',
 '2020-01-05 06:00:00',
 '2020-01-05 07:00:00',
 '2020-01-05 08:00:00',
 '2020-01-05 09:00:00',
 '2020-01-05 10:00:00',
 '2020-01-05 11:00:00',
 '2020-01-05 12:00:00',
 '2020-01-05 13:00:00',
 '2020-01-05 14:00:00',
 '2020-01-05 15:00:00',
 '2020-01-05 16:00:00',
 '2020-01-05 17:00:00',
 '2020-01-05 18:00:00',
 '2020-01-05 19:00:00',
 '2020-01-05 20:00:00',
 '2020-01-05 21:00:00',
 '2020-01-05 22:00:00',
 '2020-01-05 23:00:00',
 '2020-01-06 00:00:00',
 '2020-01-06 01:00:00',
 '2020-01-06 02:00:00',
 '2020-01-06 03:00:00',
 '2020-01-06 04:00:00',
 '2020-01-06 05:00:00',
 '2020-01-06 06:00:00',
 '2020-01-06 07:00:00',
 '2020-01-06 08:00:00',
 '2020-01-06 09:00:00',
 '2020-01-06 10:00:00',
 '2020-01-06 11:00:00',
 '2020-01-06 12:00:00',
 '2020-01-06 13:00:00',
 '2020-01-06 14:00:00',
 '2020-01-06 15:00:00',
 '2020-01-06 16:00:00',
 '2020-01-06 17:00:00',
 '2020-01-06 18:00:00',
 '2020-01-06 19:00:00',
 '2020-01-06 20:00:00',
 '2020-01-06 21:00:00',
 '2020-01-06 22:00:00',
 '2020-01-06 23:00:00',
 '2020-01-07 00:00:00',
 '2020-01-07 01:00:00',
 '2020-01-07 02:00:00',
 '2020-01-07 03:00:00',
 '2020-01-07 04:00:00',
 '2020-01-07 05:00:00',
 '2020-01-07 06:00:00',
 '2020-01-07 07:00:00',
 '2020-01-07 08:00:00',
 '2020-01-07 09:00:00',
 '2020-01-07 10:00:00',
 '2020-01-07 11:00:00',
 '2020-01-07 12:00:00',
 '2020-01-07 13:00:00',
 '2020-01-07 14:00:00',
 '2020-01-07 15:00:00',
 '2020-01-07 16:00:00',
 '2020-01-07 17:00:00',
 '2020-01-07 18:00:00',
 '2020-01-07 19:00:00',
 '2020-01-07 20:00:00',
 '2020-01-07 21:00:00',
 '2020-01-07 22:00:00',
 '2020-01-07 23:00:00',
 '2020-01-08 00:00:00',
 '2020-01-08 01:00:00',
 '2020-01-08 02:00:00',
 '2020-01-08 03:00:00',
 '2020-01-08 04:00:00',
 '2020-01-08 05:00:00',
 '2020-01-08 06:00:00',
 '2020-01-08 07:00:00',
 '2020-01-08 08:00:00',
 '2020-01-08 09:00:00',
 '2020-01-08 10:00:00',
 '2020-01-08 11:00:00',
 '2020-01-08 12:00:00',
 '2020-01-08 13:00:00',
 '2020-01-08 14:00:00',
 '2020-01-08 15:00:00',
 '2020-01-08 16:00:00',
 '2020-01-08 17:00:00',
 '2020-01-08 18:00:00',
 '2020-01-08 19:00:00',
 '2020-01-08 20:00:00',
 '2020-01-08 21:00:00',
 '2020-01-08 22:00:00',
 '2020-01-08 23:00:00',
 '2020-01-09 00:00:00',
 '2020-01-09 01:00:00',
 '2020-01-09 02:00:00',
 '2020-01-09 03:00:00',
 '2020-01-09 04:00:00',
 '2020-01-09 05:00:00',
 '2020-01-09 06:00:00',
 '2020-01-09 07:00:00',
 '2020-01-09 08:00:00',
 '2020-01-09 09:00:00',
 '2020-01-09 10:00:00',
 '2020-01-09 11:00:00',
 '2020-01-09 12:00:00',
 '2020-01-09 13:00:00',
 '2020-01-09 14:00:00',
 '2020-01-09 15:00:00',
 '2020-01-09 16:00:00',
 '2020-01-09 17:00:00',
 '2020-01-09 18:00:00',
 '2020-01-09 19:00:00',
 '2020-01-09 20:00:00',
 '2020-01-09 21:00:00',
 '2020-01-09 22:00:00',
 '2020-01-09 23:00:00',
 '2020-01-10 00:00:00',
 '2020-01-10 01:00:00',
 '2020-01-10 02:00:00',
 '2020-01-10 03:00:00',
 '2020-01-10 04:00:00',
 '2020-01-10 05:00:00',
 '2020-01-10 06:00:00',
 '2020-01-10 07:00:00',
 '2020-01-10 08:00:00',
 '2020-01-10 09:00:00',
 '2020-01-10 10:00:00',
 '2020-01-10 11:00:00',
 '2020-01-10 12:00:00',
 '2020-01-10 13:00:00',
 '2020-01-10 14:00:00',
 '2020-01-10 15:00:00',
 '2020-01-10 16:00:00',
 '2020-01-10 17:00:00',
 '2020-01-10 18:00:00',
 '2020-01-10 19:00:00',
 '2020-01-10 20:00:00',
 '2020-01-10 21:00:00',
 '2020-01-10 22:00:00',
 '2020-01-10 23:00:00',
 '2020-01-11 00:00:00',
 '2020-01-11 01:00:00',
 '2020-01-11 02:00:00',
 '2020-01-11 03:00:00',
 '2020-01-11 04:00:00',
 '2020-01-11 05:00:00',
 '2020-01-11 06:00:00',
 '2020-01-11 07:00:00',
 '2020-01-11 08:00:00',
 '2020-01-11 09:00:00',
 '2020-01-11 10:00:00',
 '2020-01-11 11:00:00',
 '2020-01-11 12:00:00',
 '2020-01-11 13:00:00',
 '2020-01-11 14:00:00',
 '2020-01-11 15:00:00',
 '2020-01-11 16:00:00',
 '2020-01-11 17:00:00',
 '2020-01-11 18:00:00',
 '2020-01-11 19:00:00',
 '2020-01-11 20:00:00',
 '2020-01-11 21:00:00',
 '2020-01-11 22:00:00',
 '2020-01-11 23:00:00',
 '2020-01-12 00:00:00',
 '2020-01-12 01:00:00',
 '2020-01-12 02:00:00',
 '2020-01-12 03:00:00',
 '2020-01-12 04:00:00',
 '2020-01-12 05:00:00',
 '2020-01-12 06:00:00',
 '2020-01-12 07:00:00',
 '2020-01-12 08:00:00',
 '2020-01-12 09:00:00',
 '2020-01-12 10:00:00',
 '2020-01-12 11:00:00',
 '2020-01-12 12:00:00',
 '2020-01-12 13:00:00',
 '2020-01-12 14:00:00',
 '2020-01-12 15:00:00',
 '2020-01-12 16:00:00',
 '2020-01-12 17:00:00',
 '2020-01-12 18:00:00',
 '2020-01-12 19:00:00',
 '2020-01-12 20:00:00',
 '2020-01-12 21:00:00',
 '2020-01-12 22:00:00',
 '2020-01-12 23:00:00',
 '2020-01-13 00:00:00',
 '2020-01-13 01:00:00',
 '2020-01-13 02:00:00',
 '2020-01-13 03:00:00',
 '2020-01-13 04:00:00',
 '2020-01-13 05:00:00',
 '2020-01-13 06:00:00',
 '2020-01-13 07:00:00',
 '2020-01-13 08:00:00',
 '2020-01-13 09:00:00',
 '2020-01-13 10:00:00',
 '2020-01-13 11:00:00',
 '2020-01-13 12:00:00',
 '2020-01-13 13:00:00',
 '2020-01-13 14:00:00',
 '2020-01-13 15:00:00',
 '2020-01-13 16:00:00',
 '2020-01-13 17:00:00',
 '2020-01-13 18:00:00',
 '2020-01-13 19:00:00',
 '2020-01-13 20:00:00',
 '2020-01-13 21:00:00',
 '2020-01-13 22:00:00',
 '2020-01-13 23:00:00',
 '2020-01-14 00:00:00',
 '2020-01-14 01:00:00',
 '2020-01-14 02:00:00',
 '2020-01-14 03:00:00',
 '2020-01-14 04:00:00',
 '2020-01-14 05:00:00',
 '2020-01-14 06:00:00',
 '2020-01-14 07:00:00',
 '2020-01-14 08:00:00',
 '2020-01-14 09:00:00',
 '2020-01-14 10:00:00',
 '2020-01-14 11:00:00',
 '2020-01-14 12:00:00',
 '2020-01-14 13:00:00',
 '2020-01-14 14:00:00',
 '2020-01-14 15:00:00',
 '2020-01-14 16:00:00',
 '2020-01-14 17:00:00',
 '2020-01-14 18:00:00',
 '2020-01-14 19:00:00',
 '2020-01-14 20:00:00',
 '2020-01-14 21:00:00',
 '2020-01-14 22:00:00',
 '2020-01-14 23:00:00',
 '2020-01-15 00:00:00',
 '2020-01-15 01:00:00',
 '2020-01-15 02:00:00',
 '2020-01-15 03:00:00',
 '2020-01-15 04:00:00',
 '2020-01-15 05:00:00',
 '2020-01-15 06:00:00',
 '2020-01-15 07:00:00',
 '2020-01-15 08:00:00',
 '2020-01-15 09:00:00',
 '2020-01-15 10:00:00',
 '2020-01-15 11:00:00',
 '2020-01-15 12:00:00',
 '2020-01-15 13:00:00',
 '2020-01-15 14:00:00',
 '2020-01-15 15:00:00',
 '2020-01-15 16:00:00',
 '2020-01-15 17:00:00',
 '2020-01-15 18:00:00',
 '2020-01-15 19:00:00',
 '2020-01-15 20:00:00',
 '2020-01-15 21:00:00',
 '2020-01-15 22:00:00',
 '2020-01-15 23:00:00',
 '2020-01-16 00:00:00',
 '2020-01-16 01:00:00',
 '2020-01-16 02:00:00',
 '2020-01-16 03:00:00',
 '2020-01-16 04:00:00',
 '2020-01-16 05:00:00',
 '2020-01-16 06:00:00',
 '2020-01-16 07:00:00',
 '2020-01-16 08:00:00',
 '2020-01-16 09:00:00',
 '2020-01-16 10:00:00',
 '2020-01-16 11:00:00',
 '2020-01-16 12:00:00',
 '2020-01-16 13:00:00',
 '2020-01-16 14:00:00',
 '2020-01-16 15:00:00',
 '2020-01-16 16:00:00',
 '2020-01-16 17:00:00',
 '2020-01-16 18:00:00',
 '2020-01-16 19:00:00',
 '2020-01-16 20:00:00',
 '2020-01-16 21:00:00',
 '2020-01-16 22:00:00',
 '2020-01-16 23:00:00',
 '2020-01-17 00:00:00',
 '2020-01-17 01:00:00',
 '2020-01-17 02:00:00',
 '2020-01-17 03:00:00',
 '2020-01-17 04:00:00',
 '2020-01-17 05:00:00',
 '2020-01-17 06:00:00',
 '2020-01-17 07:00:00',
 '2020-01-17 08:00:00',
 '2020-01-17 09:00:00',
 '2020-01-17 10:00:00',
 '2020-01-17 11:00:00',
 '2020-01-17 12:00:00',
 '2020-01-17 13:00:00',
 '2020-01-17 14:00:00',
 '2020-01-17 15:00:00',
 '2020-01-17 16:00:00',
 '2020-01-17 17:00:00',
 '2020-01-17 18:00:00',
 '2020-01-17 19:00:00',
 '2020-01-17 20:00:00',
 '2020-01-17 21:00:00',
 '2020-01-17 22:00:00',
 '2020-01-17 23:00:00',
 '2020-01-18 00:00:00',
 '2020-01-18 01:00:00',
 '2020-01-18 02:00:00',
 '2020-01-18 03:00:00',
 '2020-01-18 04:00:00',
 '2020-01-18 05:00:00',
 '2020-01-18 06:00:00',
 '2020-01-18 07:00:00',
 '2020-01-18 08:00:00',
 '2020-01-18 09:00:00',
 '2020-01-18 10:00:00',
 '2020-01-18 11:00:00',
 '2020-01-18 12:00:00',
 '2020-01-18 13:00:00',
 '2020-01-18 14:00:00',
 '2020-01-18 15:00:00',
 '2020-01-18 16:00:00',
 '2020-01-18 17:00:00',
 '2020-01-18 18:00:00',
 '2020-01-18 19:00:00',
 '2020-01-18 20:00:00',
 '2020-01-18 21:00:00',
 '2020-01-18 22:00:00',
 '2020-01-18 23:00:00',
 '2020-01-19 00:00:00',
 '2020-01-19 01:00:00',
 '2020-01-19 02:00:00',
 '2020-01-19 03:00:00',
 '2020-01-19 04:00:00',
 '2020-01-19 05:00:00',
 '2020-01-19 06:00:00',
 '2020-01-19 07:00:00',
 '2020-01-19 08:00:00',
 '2020-01-19 09:00:00',
 '2020-01-19 10:00:00',
 '2020-01-19 11:00:00',
 '2020-01-19 12:00:00',
 '2020-01-19 13:00:00',
 '2020-01-19 14:00:00',
 '2020-01-19 15:00:00',
 '2020-01-19 16:00:00',
 '2020-01-19 17:00:00',
 '2020-01-19 18:00:00',
 '2020-01-19 19:00:00',
 '2020-01-19 20:00:00',
 '2020-01-19 21:00:00',
 '2020-01-19 22:00:00',
 '2020-01-19 23:00:00',
 '2020-01-20 00:00:00',
 '2020-01-20 01:00:00',
 '2020-01-20 02:00:00',
 '2020-01-20 03:00:00',
 '2020-01-20 04:00:00',
 '2020-01-20 05:00:00',
 '2020-01-20 06:00:00',
 '2020-01-20 07:00:00',
 '2020-01-20 08:00:00',
 '2020-01-20 09:00:00',
 '2020-01-20 10:00:00',
 '2020-01-20 11:00:00',
 '2020-01-20 12:00:00',
 '2020-01-20 13:00:00',
 '2020-01-20 14:00:00',
 '2020-01-20 15:00:00',
 '2020-01-20 16:00:00',
 '2020-01-20 17:00:00',
 '2020-01-20 18:00:00',
 '2020-01-20 19:00:00',
 '2020-01-20 20:00:00',
 '2020-01-20 21:00:00',
 '2020-01-20 22:00:00',
 '2020-01-20 23:00:00',
 '2020-01-21 00:00:00',
 '2020-01-21 01:00:00',
 '2020-01-21 02:00:00',
 '2020-01-21 03:00:00',
 '2020-01-21 04:00:00',
 '2020-01-21 05:00:00',
 '2020-01-21 06:00:00',
 '2020-01-21 07:00:00',
 '2020-01-21 08:00:00',
 '2020-01-21 09:00:00',
 '2020-01-21 10:00:00',
 '2020-01-21 11:00:00',
 '2020-01-21 12:00:00',
 '2020-01-21 13:00:00',
 '2020-01-21 14:00:00',
 '2020-01-21 15:00:00',
 '2020-01-21 16:00:00',
 '2020-01-21 17:00:00',
 '2020-01-21 18:00:00',
 '2020-01-21 19:00:00',
 '2020-01-21 20:00:00',
 '2020-01-21 21:00:00',
 '2020-01-21 22:00:00',
 '2020-01-21 23:00:00',
 '2020-01-22 00:00:00',
 '2020-01-22 01:00:00',
 '2020-01-22 02:00:00',
 '2020-01-22 03:00:00',
 '2020-01-22 04:00:00',
 '2020-01-22 05:00:00',
 '2020-01-22 06:00:00',
 '2020-01-22 07:00:00',
 '2020-01-22 08:00:00',
 '2020-01-22 09:00:00',
 '2020-01-22 10:00:00',
 '2020-01-22 11:00:00',
 '2020-01-22 12:00:00',
 '2020-01-22 13:00:00',
 '2020-01-22 14:00:00',
 '2020-01-22 15:00:00',
 '2020-01-22 16:00:00',
 '2020-01-22 17:00:00',
 '2020-01-22 18:00:00',
 '2020-01-22 19:00:00',
 '2020-01-22 20:00:00',
 '2020-01-22 21:00:00',
 '2020-01-22 22:00:00',
 '2020-01-22 23:00:00',
 '2020-01-23 00:00:00',
 '2020-01-23 01:00:00',
 '2020-01-23 02:00:00',
 '2020-01-23 03:00:00',
 '2020-01-23 04:00:00',
 '2020-01-23 05:00:00',
 '2020-01-23 06:00:00',
 '2020-01-23 07:00:00',
 '2020-01-23 08:00:00',
 '2020-01-23 09:00:00',
 '2020-01-23 10:00:00',
 '2020-01-23 11:00:00',
 '2020-01-23 12:00:00',
 '2020-01-23 13:00:00',
 '2020-01-23 14:00:00',
 '2020-01-23 15:00:00',
 '2020-01-23 16:00:00',
 '2020-01-23 17:00:00',
 '2020-01-23 18:00:00',
 '2020-01-23 19:00:00',
 '2020-01-23 20:00:00',
 '2020-01-23 21:00:00',
 '2020-01-23 22:00:00',
 '2020-01-23 23:00:00',
 '2020-01-24 00:00:00',
 '2020-01-24 01:00:00',
 '2020-01-24 02:00:00',
 '2020-01-24 03:00:00',
 '2020-01-24 04:00:00',
 '2020-01-24 05:00:00',
 '2020-01-24 06:00:00',
 '2020-01-24 07:00:00',
 '2020-01-24 08:00:00',
 '2020-01-24 09:00:00',
 '2020-01-24 10:00:00',
 '2020-01-24 11:00:00',
 '2020-01-24 12:00:00',
 '2020-01-24 13:00:00',
 '2020-01-24 14:00:00',
 '2020-01-24 15:00:00',
 '2020-01-24 16:00:00',
 '2020-01-24 17:00:00',
 '2020-01-24 18:00:00',
 '2020-01-24 19:00:00',
 '2020-01-24 20:00:00',
 '2020-01-24 21:00:00',
 '2020-01-24 22:00:00',
 '2020-01-24 23:00:00',
 '2020-01-25 00:00:00',
 '2020-01-25 01:00:00',
 '2020-01-25 02:00:00',
 '2020-01-25 03:00:00',
 '2020-01-25 04:00:00',
 '2020-01-25 05:00:00',
 '2020-01-25 06:00:00',
 '2020-01-25 07:00:00',
 '2020-01-25 08:00:00',
 '2020-01-25 09:00:00',
 '2020-01-25 10:00:00',
 '2020-01-25 11:00:00',
 '2020-01-25 12:00:00',
 '2020-01-25 13:00:00',
 '2020-01-25 14:00:00',
 '2020-01-25 15:00:00',
 '2020-01-25 16:00:00',
 '2020-01-25 17:00:00',
 '2020-01-25 18:00:00',
 '2020-01-25 19:00:00',
 '2020-01-25 20:00:00',
 '2020-01-25 21:00:00',
 '2020-01-25 22:00:00',
 '2020-01-25 23:00:00',
 '2020-01-26 00:00:00',
 '2020-01-26 01:00:00',
 '2020-01-26 02:00:00',
 '2020-01-26 03:00:00',
 '2020-01-26 04:00:00',
 '2020-01-26 05:00:00',
 '2020-01-26 06:00:00',
 '2020-01-26 07:00:00',
 '2020-01-26 08:00:00',
 '2020-01-26 09:00:00',
 '2020-01-26 10:00:00',
 '2020-01-26 11:00:00',
 '2020-01-26 12:00:00',
 '2020-01-26 13:00:00',
 '2020-01-26 14:00:00',
 '2020-01-26 15:00:00',
 '2020-01-26 16:00:00',
 '2020-01-26 17:00:00',
 '2020-01-26 18:00:00',
 '2020-01-26 19:00:00',
 '2020-01-26 20:00:00',
 '2020-01-26 21:00:00',
 '2020-01-26 22:00:00',
 '2020-01-26 23:00:00',
 '2020-01-27 00:00:00',
 '2020-01-27 01:00:00',
 '2020-01-27 02:00:00',
 '2020-01-27 03:00:00',
 '2020-01-27 04:00:00',
 '2020-01-27 05:00:00',
 '2020-01-27 06:00:00',
 '2020-01-27 07:00:00',
 '2020-01-27 08:00:00',
 '2020-01-27 09:00:00',
 '2020-01-27 10:00:00',
 '2020-01-27 11:00:00',
 '2020-01-27 12:00:00',
 '2020-01-27 13:00:00',
 '2020-01-27 14:00:00',
 '2020-01-27 15:00:00',
 '2020-01-27 16:00:00',
 '2020-01-27 17:00:00',
 '2020-01-27 18:00:00',
 '2020-01-27 19:00:00',
 '2020-01-27 20:00:00',
 '2020-01-27 21:00:00',
 '2020-01-27 22:00:00',
 '2020-01-27 23:00:00',
 '2020-01-28 00:00:00',
 '2020-01-28 01:00:00',
 '2020-01-28 02:00:00',
 '2020-01-28 03:00:00',
 '2020-01-28 04:00:00',
 '2020-01-28 05:00:00',
 '2020-01-28 06:00:00',
 '2020-01-28 07:00:00',
 '2020-01-28 08:00:00',
 '2020-01-28 09:00:00',
 '2020-01-28 10:00:00',
 '2020-01-28 11:00:00',
 '2020-01-28 12:00:00',
 '2020-01-28 13:00:00',
 '2020-01-28 14:00:00',
 '2020-01-28 15:00:00',
 '2020-01-28 16:00:00',
 '2020-01-28 17:00:00',
 '2020-01-28 18:00:00',
 '2020-01-28 19:00:00',
 '2020-01-28 20:00:00',
 '2020-01-28 21:00:00',
 '2020-01-28 22:00:00',
 '2020-01-28 23:00:00',
 '2020-01-29 00:00:00',
 '2020-01-29 01:00:00',
 '2020-01-29 02:00:00',
 '2020-01-29 03:00:00',
 '2020-01-29 04:00:00',
 '2020-01-29 05:00:00',
 '2020-01-29 06:00:00',
 '2020-01-29 07:00:00',
 '2020-01-29 08:00:00',
 '2020-01-29 09:00:00',
 '2020-01-29 10:00:00',
 '2020-01-29 11:00:00',
 '2020-01-29 12:00:00',
 '2020-01-29 13:00:00',
 '2020-01-29 14:00:00',
 '2020-01-29 15:00:00',
 '2020-01-29 16:00:00',
 '2020-01-29 17:00:00',
 '2020-01-29 18:00:00',
 '2020-01-29 19:00:00',
 '2020-01-29 20:00:00',
 '2020-01-29 21:00:00',
 '2020-01-29 22:00:00',
 '2020-01-29 23:00:00',
 '2020-01-30 00:00:00',
 '2020-01-30 01:00:00',
 '2020-01-30 02:00:00',
 '2020-01-30 03:00:00',
 '2020-01-30 04:00:00',
 '2020-01-30 05:00:00',
 '2020-01-30 06:00:00',
 '2020-01-30 07:00:00',
 '2020-01-30 08:00:00',
 '2020-01-30 09:00:00',
 '2020-01-30 10:00:00',
 '2020-01-30 11:00:00',
 '2020-01-30 12:00:00',
 '2020-01-30 13:00:00',
 '2020-01-30 14:00:00',
 '2020-01-30 15:00:00',
 '2020-01-30 16:00:00',
 '2020-01-30 17:00:00',
 '2020-01-30 18:00:00',
 '2020-01-30 19:00:00',
 '2020-01-30 20:00:00',
 '2020-01-30 21:00:00',
 '2020-01-30 22:00:00',
 '2020-01-30 23:00:00',
 '2020-01-31 00:00:00',
 '2020-01-31 01:00:00',
 '2020-01-31 02:00:00',
 '2020-01-31 03:00:00',
 '2020-01-31 04:00:00',
 '2020-01-31 05:00:00',
 '2020-01-31 06:00:00',
 '2020-01-31 07:00:00',
 '2020-01-31 08:00:00',
 '2020-01-31 09:00:00',
 '2020-01-31 10:00:00',
 '2020-01-31 11:00:00',
 '2020-01-31 12:00:00',
 '2020-01-31 13:00:00',
 '2020-01-31 14:00:00',
 '2020-01-31 15:00:00',
 '2020-01-31 16:00:00',
 '2020-01-31 17:00:00',
 '2020-01-31 18:00:00',
 '2020-01-31 19:00:00',
 '2020-01-31 20:00:00',
 '2020-01-31 21:00:00',
 '2020-01-31 22:00:00',
 '2020-01-31 23:00:00',
 '2020-02-01 00:00:00',
 '2020-02-01 01:00:00',
 '2020-02-01 02:00:00',
 '2020-02-01 03:00:00',
 '2020-02-01 04:00:00',
 '2020-02-01 05:00:00',
 '2020-02-01 06:00:00',
 '2020-02-01 07:00:00',
 '2020-02-01 08:00:00',
 '2020-02-01 09:00:00',
 '2020-02-01 10:00:00',
 '2020-02-01 11:00:00',
 '2020-02-01 12:00:00',
 '2020-02-01 13:00:00',
 '2020-02-01 14:00:00',
 '2020-02-01 15:00:00',
 '2020-02-01 16:00:00',
 '2020-02-01 17:00:00',
 '2020-02-01 18:00:00',
 '2020-02-01 19:00:00',
 '2020-02-01 20:00:00',
 '2020-02-01 21:00:00',
 '2020-02-01 22:00:00',
 '2020-02-01 23:00:00',
 '2020-02-02 00:00:00',
 '2020-02-02 01:00:00',
 '2020-02-02 02:00:00',
 '2020-02-02 03:00:00',
 '2020-02-02 04:00:00',
 '2020-02-02 05:00:00',
 '2020-02-02 06:00:00',
 '2020-02-02 07:00:00',
 '2020-02-02 08:00:00',
 '2020-02-02 09:00:00',
 '2020-02-02 10:00:00',
 '2020-02-02 11:00:00',
 '2020-02-02 12:00:00',
 '2020-02-02 13:00:00',
 '2020-02-02 14:00:00',
 '2020-02-02 15:00:00',
 '2020-02-02 16:00:00',
 '2020-02-02 17:00:00',
 '2020-02-02 18:00:00',
 '2020-02-02 19:00:00',
 '2020-02-02 20:00:00',
 '2020-02-02 21:00:00',
 '2020-02-02 22:00:00',
 '2020-02-02 23:00:00',
 '2020-02-03 00:00:00',
 '2020-02-03 01:00:00',
 '2020-02-03 02:00:00',
 '2020-02-03 03:00:00',
 '2020-02-03 04:00:00',
 '2020-02-03 05:00:00',
 '2020-02-03 06:00:00',
 '2020-02-03 07:00:00',
 '2020-02-03 08:00:00',
 '2020-02-03 09:00:00',
 '2020-02-03 10:00:00',
 '2020-02-03 11:00:00',
 '2020-02-03 12:00:00',
 '2020-02-03 13:00:00',
 '2020-02-03 14:00:00',
 '2020-02-03 15:00:00',
 '2020-02-03 16:00:00',
 '2020-02-03 17:00:00',
 '2020-02-03 18:00:00',
 '2020-02-03 19:00:00',
 '2020-02-03 20:00:00',
 '2020-02-03 21:00:00',
 '2020-02-03 22:00:00',
 '2020-02-03 23:00:00',
 '2020-02-04 00:00:00',
 '2020-02-04 01:00:00',
 '2020-02-04 02:00:00',
 '2020-02-04 03:00:00',
 '2020-02-04 04:00:00',
 '2020-02-04 05:00:00',
 '2020-02-04 06:00:00',
 '2020-02-04 07:00:00',
 '2020-02-04 08:00:00',
 '2020-02-04 09:00:00',
 '2020-02-04 10:00:00',
 '2020-02-04 11:00:00',
 '2020-02-04 12:00:00',
 '2020-02-04 13:00:00',
 '2020-02-04 14:00:00',
 '2020-02-04 15:00:00',
 '2020-02-04 16:00:00',

In [11]:
type(string_date_rng[0])

str

In [12]:
#convert the strings to the time stamp
timestamp_date_rng=pd.to_datetime(string_date_rng)
timestamp_date_rng

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00', '2020-01-01 07:00:00',
               '2020-01-01 08:00:00', '2020-01-01 09:00:00',
               ...
               '2020-12-30 15:00:00', '2020-12-30 16:00:00',
               '2020-12-30 17:00:00', '2020-12-30 18:00:00',
               '2020-12-30 19:00:00', '2020-12-30 20:00:00',
               '2020-12-30 21:00:00', '2020-12-30 22:00:00',
               '2020-12-30 23:00:00', '2020-12-31 00:00:00'],
              dtype='datetime64[ns]', length=8761, freq=None)

**FILTERING**

In [13]:
#we want to observe all the timestamps on the second day of a month
df[df.index.day==2]

                     data
datetime
2020-01-02 00:00:00    42
2020-01-02 01:00:00    94
2020-01-02 02:00:00    99
2020-01-02 03:00:00     7
2020-01-02 04:00:00    84
...                   ...
2020-12-02 19:00:00    83
2020-12-02 20:00:00    26
2020-12-02 21:00:00    87
2020-12-02 22:00:00    12
2020-12-02 23:00:00     8

[288 rows x 1 columns]

In [14]:
#if we wnat to observe at a particular date
df['2020-2-2']

                     data
datetime
2020-02-02 00:00:00     5
2020-02-02 01:00:00    64
2020-02-02 02:00:00    65
2020-02-02 03:00:00    66
2020-02-02 04:00:00    41
2020-02-02 05:00:00    51
2020-02-02 06:00:00    28
2020-02-02 07:00:00    97
2020-02-02 08:00:00    34
2020-02-02 09:00:00    58
2020-02-02 10:00:00    61
2020-02-02 11:00:00    62
2020-02-02 12:00:00    97
2020-02-02 13:00:00    21
2020-02-02 14:00:00    46
2020-02-02 15:00:00     2
2020-02-02 16:00:00    14
2020-02-02 17:00:00    51
2020-02-02 18:00:00    68
2020-02-02 19:00:00    95
2020-02-02 20:00:00    45
2020-02-02 21:00:00    79
2020-02-02 22:00:00    83
2020-02-02 23:00:00    53

In [15]:
#we want to observe all the timestamps in 2 particular periods
df['2020-2-2':'2020-6-11']

                     data
datetime
2020-02-02 00:00:00     5
2020-02-02 01:00:00    64
2020-02-02 02:00:00    65
2020-02-02 03:00:00    66
2020-02-02 04:00:00    41
...                   ...
2020-06-11 19:00:00    11
2020-06-11 20:00:00     6
2020-06-11 21:00:00    35
2020-06-11 22:00:00    96
2020-06-11 23:00:00    82

[3144 rows x 1 columns]

**RESAMPLING**

In [16]:
#resample dataset according to different frequencies
df.resample('D').mean()#D-Day, mean of each day

                 data
datetime
2020-01-01  44.833333
2020-01-02  49.375000
2020-01-03  53.458333
2020-01-04  48.000000
2020-01-05  48.875000
...               ...
2020-12-27  54.750000
2020-12-28  57.708333
2020-12-29  52.416667
2020-12-30  54.333333
2020-12-31  31.000000

[366 rows x 1 columns]

In [17]:
df.resample('M').mean()#M-Month, mean of each month

                 data
datetime
2020-01-31  47.923387
2020-02-29  50.455460
2020-03-31  49.920699
2020-04-30  49.563889
2020-05-31  51.361559
2020-06-30  50.766667
2020-07-31  47.211022
2020-08-31  48.454301
2020-09-30  48.476389
2020-10-31  48.864247
2020-11-30  48.568056
2020-12-31  51.592233

**WINDOW STATISTICS-ROLLING MEAN AND ROLLING SUM**

In [18]:
#let's create a new column in our original df that computes the rolling sum over a period window
#take 3 period window
df['rolling_sum']=df.rolling(3).sum()
df.head(10)

                     data  rolling_sum
datetime
2020-01-01 00:00:00    77          NaN
2020-01-01 01:00:00    31          NaN
2020-01-01 02:00:00    65        173.0
2020-01-01 03:00:00    10        106.0
2020-01-01 04:00:00    43        118.0
2020-01-01 05:00:00    61        114.0
2020-01-01 06:00:00    64        168.0
2020-01-01 07:00:00    86        211.0
2020-01-01 08:00:00    78        228.0
2020-01-01 09:00:00     0        164.0

**HANDLING MISSING DATA**

In [19]:
#'backfill' for preceding NaN values
#'forwardfill' for succeding NaN values
df['rolling_sum_backfilled']=df['rolling_sum'].fillna(method='backfill')
df.head(10)

                     data  rolling_sum  rolling_sum_backfilled
datetime
2020-01-01 00:00:00    77          NaN                   173.0
2020-01-01 01:00:00    31          NaN                   173.0
2020-01-01 02:00:00    65        173.0                   173.0
2020-01-01 03:00:00    10        106.0                   106.0
2020-01-01 04:00:00    43        118.0                   118.0
2020-01-01 05:00:00    61        114.0                   114.0
2020-01-01 06:00:00    64        168.0                   168.0
2020-01-01 07:00:00    86        211.0                   211.0
2020-01-01 08:00:00    78        228.0                   228.0
2020-01-01 09:00:00     0        164.0                   164.0